#!/usr/bin/env python3
"""Writes netlify.toml for hosting this folder as its own Netlify site (base directory:
prototypes/alcedo-website). Security headers include a strict Content-Security-Policy:
scripts are allowed only by the SHA-256 hash of each inline <script> in index.html and
privacy.html, so re-run this after editing any inline script:

    python3 tools/build_netlify_toml.py
"""
import base64, hashlib, pathlib, re

HERE = pathlib.Path(__file__).resolve().parent.parent
hashes = []
for page in ('index.html', 'privacy.html'):
    html = re.sub(r'<!--.*?-->', '', (HERE / page).read_text(), flags=re.S)   # comments may mention <script>
    for body in re.findall(r'<script>(.*?)</script>', html, re.S):
        h = "'sha256-" + base64.b64encode(hashlib.sha256(body.encode()).digest()).decode() + "'"
        if h not in hashes:
            hashes.append(h)
csp = '; '.join([
    "default-src 'self'",
    "script-src 'self' " + ' '.join(hashes),
    "style-src 'self' 'unsafe-inline'",          # inline <style> and style="--d:…" attributes
    "img-src 'self' data:",
    "media-src 'self' data:",
    "font-src 'self'",
    "connect-src 'none'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'none'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
])
toml = f'''# Generated by tools/build_netlify_toml.py. Do not edit the CSP by hand.
# Deploy this folder as its own Netlify site: base directory "prototypes/alcedo-website",
# no build command, publish directory "." (the folder itself).
[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "{csp}"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), interest-cohort=()"
    Cross-Origin-Opener-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# The build tools, notes and source masters are not part of the public site.
[[redirects]]
  from = "/tools/*"
  to = "/404.html"
  status = 404
  force = true
[[redirects]]
  from = "/*.md"
  to = "/404.html"
  status = 404
  force = true
'''
(HERE / 'netlify.toml').write_text(toml)
print(len(hashes), 'inline script hashes ->', HERE / 'netlify.toml')
