#!/usr/bin/env python3
"""Writes INVENTORY.md: every file this review branch adds or changes relative to origin/main,
with size, sha256, whether the Alcedo page references it, and where it came from.

    git fetch origin main && git add -A prototypes && python3 prototypes/alcedo-website/tools/build_inventory.py
"""
import hashlib, pathlib, subprocess

ROOT = pathlib.Path(subprocess.check_output(['git', 'rev-parse', '--show-toplevel'], text=True).strip())
HERE = ROOT / 'prototypes/alcedo-website'
import re
html = re.sub(r'<!--.*?-->', '', (HERE / 'index.html').read_text(), flags=re.S)
# real references only (src/href attributes and CSS url()), not mentions in comments
page = set(re.findall(r'(?:src|href)="(assets/[^"]+)"', html) + re.findall(r'url\("(assets/[^"]+)"\)', html))
base = subprocess.check_output(['git', 'merge-base', 'origin/main', 'HEAD'], cwd=ROOT, text=True).strip()
rows = subprocess.check_output(['git', 'diff', '--cached', '--name-status', '--no-renames', base], cwd=ROOT, text=True).split('\n')

KIT = 'ALCEDO Logo Kit v1.0 (supplied zip), byte-identical copy'
def provenance(rel):
    name = rel.split('/')[-1]
    if rel.startswith('prototypes/atlas-website/'):
        return 'Authored: Atlas-branded prototype (first request); brand kit files embedded as data URIs'
    if rel.endswith('assets/hero.mp4'): return 'Supplied upload, byte-identical (H.264 High, 1280×720, 24 fps, 8.0 s)'
    if rel.endswith('hero-final.webp'): return 'Derived: last frame (8.00 s) of hero.mp4, ffmpeg extract, WebP q80'
    if 'alcedo-horizontal-' in name: return 'Derived: kit symbol + outlined wordmark paths, uniform scale/translate only (tools/build_horizontal_lockup.py)'
    if '/assets/brand/' in rel: return KIT
    if name == 'alcedo-kingfisher-master.webp': return 'Supplied approved mascot master, byte-identical (1214×1295, genuine alpha)'
    if '/assets/mascot/' in rel: return 'Derived: mascot master, alpha clean-up and rectangular crop only (tools/build_mascot_assets.py)'
    if '/assets/screens/' in rel: return 'Captured: apps/web in the mocked test harness, fictional sample data, WebP 1600×1000'
    if '/tools/' in rel: return 'Authored: build/verification tool'
    return 'Authored'

lines = ['# File and asset inventory — review branch', '',
         f'Every file this branch adds or changes relative to its base `{base[:7]}` on `origin/main` (generated by `tools/build_inventory.py`).',
         'Nothing outside `prototypes/` is changed (no `apps/`, `scripts/`, `supabase/`, `tests/` or `docs/` files). Status `A` = added.', '',
         '| Status | Path | Bytes | SHA-256 | Used by Alcedo page | Provenance |', '|---|---|---:|---|---|---|']
total = 0
for row in filter(None, rows):
    status, rel = row.split('\t')
    path = ROOT / rel
    if rel.endswith('INVENTORY.md'):
        lines.append(f'| {status} | `{rel}` | — | (this file) | — | Authored |'); continue
    data = path.read_bytes(); total += len(data)
    used = '—' if not rel.startswith('prototypes/alcedo-website/assets/') else ('yes' if rel.split('prototypes/alcedo-website/')[1] in page else ('no (dark-surface deliverable)' if 'horizontal-dark' in rel else 'no (source kept for tools)'))
    lines.append(f'| {status} | `{rel}` | {len(data):,} | `{hashlib.sha256(data).hexdigest()}` | {used} | {provenance(rel)} |')
lines += ['', f'Total (excluding this file): {total:,} bytes.', '']
(HERE / 'INVENTORY.md').write_text('\n'.join(lines))
print('\n'.join(lines))
